name: Spotify Connect
version: dev
slug: spotify
description: Play Spotify music on your Home Assistant device - David
url: https://github.com/limacher58/addon-spotify-connect_more_options
codenotary: codenotary@frenck.dev
arch:
  - aarch64
  - amd64
  - armv7
host_network: true
audio: true
init: false
options:
  name: Home Assistant
  bitrate: 160
  cache-size-limit: 1M # Size can be specified with suffixes like K, M, or G
  disable-audio-cache: false
  device-type: speaker
  backend: pulseaudio
  device: default
  format: S16
  dither: auto
  initial-volume: 50
  enable-volume-normalisation: true
  autoplay: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  username: str?
  password: password?
  cache-size-limit: str # Allows for values like "1M", "512K", etc.
  disable-audio-cache: bool
  device-type: list(computer|tablet|smartphone|speaker|tv|avr|stb|audiodongle|gameconsole|castaudio|castvideo|automobile|smartwatch|chromebook|carthing|homething)
  backend: list(pulseaudio|pipe) # Restricted to valid backend types
  device: str
  format: list(F64|F32|S32|S24|S24_3|S16)
  dither: list(none|auto|triangular|gpdf|tpdf|tpdf_hp)
  initial-volume: int
  enable-volume-normalisation: bool
  autoplay: bool
